jobs:
  decrement-base-instance-count:
    runs-on: ubuntu-latest
    steps:
      - name: Get current base_instance_count
        id: get_var
        run: |
          response=$(gh api repos/${{ github.repository }}/actions/variables/base_instance_count)
          echo "value=$(echo $response | jq .value)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Decrement base_instance_count
        run: |
          new_value=$(( ${{ steps.get_var.outputs.value }} - 1 ))
          gh api --method PATCH repos/${{ github.repository }}/actions/variables/base_instance_count -f value=$new_value
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
